### PR TITLE
Fixed app crash on empty csv upload

### LINKED ISSUE #41: App crashes when pressing submit with no csv file

### PR DESCRIPTION
**Pull request by brunofbrito**
Fixes #41

### CODE REVIEW

File: app/actions.rb [hunk 1]
```diff
@@ -91,9 +91,13 @@
...
+  if params[:import]
+    party = Party.find(params[:party_id])
+    CSV.foreach(params[:import], headers: true) do |row|
+     party.attendees.create(row.to_hash)
+   end
+    redirect "/#{params[:party_id]}"
+  else
+    redirect "/#{params[:party_id]}", error: 'Please add a CSV file!'
+  end
 end
```
Comment (ricardojusto) [inline app/actions.rb:113]: great 
:+1: 
:+1:

**Comment by brunofbrito** [comment]
ok
